
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Server.Packets
{

	/// <summary>Holder for reflection information generated from protocol.proto</summary>
	public static partial class ProtocolReflection
	{

		#region Descriptor
		/// <summary>File descriptor for protocol.proto</summary>
		public static pbr::FileDescriptor Descriptor
		{
			get { return descriptor; }
		}
		private static pbr::FileDescriptor descriptor;

		static ProtocolReflection()
		{
			byte[] descriptorData = global::System.Convert.FromBase64String(
				string.Concat(
				  "Cg5wcm90b2NvbC5wcm90bxIGU2VydmVyGh9nb29nbGUvcHJvdG9idWYvdGlt",
				  "ZXN0YW1wLnByb3RvIiIKBlNfQ2hhdBIKCgJpZBgBIAEoBRIMCgRjaGF0GAIg",
				  "ASgJQhGqAg5TZXJ2ZXIuUGFja2V0c2IGcHJvdG8z"));
			descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
				new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
				new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
			new pbr::GeneratedClrTypeInfo(typeof(global::Server.Packets.S_Chat), global::Server.Packets.S_Chat.Parser, new[]{ "Id", "Chat" }, null, null, null, null)
				}));
		}
		#endregion

	}
	#region Messages
	public sealed partial class S_Chat : pb::IMessage<S_Chat>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
	  , pb::IBufferMessage
#endif
	{
		private static readonly pb::MessageParser<S_Chat> _parser = new pb::MessageParser<S_Chat>(() => new S_Chat());
		private pb::UnknownFieldSet _unknownFields;
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public static pb::MessageParser<S_Chat> Parser { get { return _parser; } }

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public static pbr::MessageDescriptor Descriptor
		{
			get { return global::Server.Packets.ProtocolReflection.Descriptor.MessageTypes[0]; }
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		pbr::MessageDescriptor pb::IMessage.Descriptor
		{
			get { return Descriptor; }
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public S_Chat()
		{
			OnConstruction();
		}

		partial void OnConstruction();

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public S_Chat(S_Chat other) : this()
		{
			id_ = other.id_;
			chat_ = other.chat_;
			_unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public S_Chat Clone()
		{
			return new S_Chat(this);
		}

		/// <summary>Field number for the "id" field.</summary>
		public const int IdFieldNumber = 1;
		private int id_;
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public int Id
		{
			get { return id_; }
			set
			{
				id_ = value;
			}
		}

		/// <summary>Field number for the "chat" field.</summary>
		public const int ChatFieldNumber = 2;
		private string chat_ = "";
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public string Chat
		{
			get { return chat_; }
			set
			{
				chat_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
			}
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public override bool Equals(object other)
		{
			return Equals(other as S_Chat);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public bool Equals(S_Chat other)
		{
			if (ReferenceEquals(other, null))
			{
				return false;
			}
			if (ReferenceEquals(other, this))
			{
				return true;
			}
			if (Id != other.Id) return false;
			if (Chat != other.Chat) return false;
			return Equals(_unknownFields, other._unknownFields);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public override int GetHashCode()
		{
			int hash = 1;
			if (Id != 0) hash ^= Id.GetHashCode();
			if (Chat.Length != 0) hash ^= Chat.GetHashCode();
			if (_unknownFields != null)
			{
				hash ^= _unknownFields.GetHashCode();
			}
			return hash;
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public override string ToString()
		{
			return pb::JsonFormatter.ToDiagnosticString(this);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public void WriteTo(pb::CodedOutputStream output)
		{
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
			output.WriteRawMessage(this);
#else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Chat.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Chat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
		}

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
		{
			if (Id != 0)
			{
				output.WriteRawTag(8);
				output.WriteInt32(Id);
			}
			if (Chat.Length != 0)
			{
				output.WriteRawTag(18);
				output.WriteString(Chat);
			}
			if (_unknownFields != null)
			{
				_unknownFields.WriteTo(ref output);
			}
		}
#endif

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public int CalculateSize()
		{
			int size = 0;
			if (Id != 0)
			{
				size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
			}
			if (Chat.Length != 0)
			{
				size += 1 + pb::CodedOutputStream.ComputeStringSize(Chat);
			}
			if (_unknownFields != null)
			{
				size += _unknownFields.CalculateSize();
			}
			return size;
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public void MergeFrom(S_Chat other)
		{
			if (other == null)
			{
				return;
			}
			if (other.Id != 0)
			{
				Id = other.Id;
			}
			if (other.Chat.Length != 0)
			{
				Chat = other.Chat;
			}
			_unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
		}

		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		public void MergeFrom(pb::CodedInputStream input)
		{
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
			input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Chat = input.ReadString();
            break;
          }
        }
      }
#endif
		}

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
		[global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
		void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
		{
			uint tag;
			while ((tag = input.ReadTag()) != 0)
			{
				switch (tag)
				{
					default:
						_unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
						break;
					case 8:
						{
							Id = input.ReadInt32();
							break;
						}
					case 18:
						{
							Chat = input.ReadString();
							break;
						}
				}
			}
		}
#endif

	}

	#endregion

}

#endregion Designer generated code
